### ISSUE TITLE
Add example.env file to MERN repository for easier configuration setup

### ISSUE THREAD

**Issue by fiskryeziu** [arpittyagi102/LinkUp#13]
### Issue Description:
Currently, the MERN repository lacks an example.env file, which makes it difficult for developers to set up and configure the application's environment variables. This issue aims to address this problem by adding an example.env file to the repository.

**Comment by frankhit2021** [comment]
I am new to the open source project, and do not know how to set up the environment variables in step 4. Could anyone offer some help? Thank you!

**Comment by arpittyagi102** [comment]
What you can do is add an Dummy value, wherever it is using environent variables, in the whole code.
You can find them by searching 
'process.env'
For example the code is 
'''bash
const value = process.env.SECRET
'''
change it to 
'''bash
const value = process.env.SECRET || "DUMMYVALUE"
'''

**Comment by frankhit2021** [comment]
Thank you! Let me try.

**Comment by Vyom-V** [comment]
-> for .env file in backend you need create it just inside the backend folder you can find the relevent path from the gitignore file
-> create 2 variables `MONGO_URI` and `DB_NAME` 
-> open up mongo compass you'll find a connection link there assign it to `MONGO_URI = "your key" `
-> after you connect compass youll find databases either create one or use the existing ones ` DB_NAME = 'you db name'`

for Front-end
-> i couldnt tell where its supposed to go but you use this `const value = process.env.SECRET || "DUMMYVALUE"`
-> you can generate your client_id by following this link: https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid
