### ISSUE TITLE
Add One-Tap Google Login

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#16]

**Comment by Hrx4** [comment]
hello can you please provide more details, I want to work on this issue.

**Comment by Vyom-V** [comment]
can you assign this to me? I think I can get this done.

**Comment by arpittyagi102** [comment]
Hello contributors, 
Use this library
```bash
import { useGoogleOneTapLogin } from '@react-oauth/google';
```
And refer to this [link](https://www.npmjs.com/package/@react-oauth/google)
And ask me if you need any help
This shouldn't take long.

**Comment by Hrx4** [comment]
Hi , i understand the problem. Assign me the issue.
