### ISSUE TITLE
create a CONTRIBUTING.md for this project

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#19]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by arpittyagi102** [comment]
Sorry, i would like to give this chance to beginner contributors as this is an easy issue

**Comment by abelchua** [comment]
first timer on an open source project, let me know what i can do to help :)

**Comment by arpittyagi102** [comment]
@abelchua, Have a look at other project's CONTRIBUTING.md understand them, and create one for this repository.

**Comment by Saagarjha1** [comment]
first timer on an open source project,Can I work on this

**Comment by asifMalik78** [comment]
cna i work on this to resolve this issue i am also first timer

**Comment by arpittyagi102** [comment]
Hello @asifMalik78, Sorry this issue is already being worked on.
