### ISSUE TITLE
Create custom alert, errors and warnings

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#3]
Hello Contributers, I want someone to add custom dropdown alerts or errors, for example, when user attempts a login and it is successfull, there should be a green minimal alert saying "Successfully logged in".
Ask me anything you need help with.

**Comment by rohitrokz29** [comment]
Hey can i work on this issue?

**Comment by asifMalik78** [comment]
I can work on this issue if it is not resolved
