### ISSUE TITLE
Add Emoji sending panel to the chatting interface

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#30]
Hello contributors, i want someone to add an emoji panel to `chat.jsx`
for reference you can take help from [This Emoji Package](https://github.com/missive/emoji-mart)
And remember to go through CONTRIBUTING.md

**Comment by Himanshu8862** [comment]
hey @arpittyagi102 Can I take up this issue? I have worked with [Emoji Picker React](https://www.npmjs.com/package/emoji-picker-react) before and can add emoji panel

**Comment by arpittyagi102** [comment]
Hello @Himanshu8862, I have assigned you the issue, you may start working on it.
