### ISSUE TITLE
Add Validator in login and signup form

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#4]
Hello contributers, i want someone to add validator in login and sign up forms.

**Comment by TechVisionWeb** [comment]
Hey - I am happy to help. This is obviously my first issue to attempt to commit to.

**Comment by arpittyagirocks** [comment]
Hello @TechVisionWeb, Welcome to the world of open source contributions, I have assigned you the issue, 
Do not hesitate to ask anything, I will try my best to help.

**Comment by TechVisionWeb** [comment]
Hi @arpittyagirocks I am not sure about the database connection URL or  JWT secret key. Is this neccesary for my contribution and if so, what information can you recommend as a source? I am looking at app.js.

**Comment by arpittyagirocks** [comment]
If you look at the "LoginPage.jsx" and "SignupPage.jsx" database is already connected for authentication.
But it still sends response to database even if input fields are empty and
also it allows to submit even if we enter any string in the email input field in Sign up page
I hope i am clear.

**Comment by TechVisionWeb** [comment]
Hello - I am going to withdraw because I wasn't aware of the use of react and JSX. I should have probably looked through some of the source code on github first

**Comment by elidakirigo** [comment]
hello, I'd like to assist in the validation of this repository, I am aware of the use of react

**Comment by arpittyagirocks** [comment]
Hello @elidakirigo, I have assigned you the issue you can start working on it.

**Comment by arpittyagirocks** [comment]
Hey @elidakirigo, I am also trying to write docs for the project on the way, You can have a look at [loginpage.md](https://github.com/arpittyagirocks/LinkUp/blob/master/docs/loginpage.md)

**Comment by elidakirigo** [comment]
thanks @arpittyagirocks  i will look at the docs before i start working on it.

**Comment by arpittyagirocks** [comment]
Hey @elidakirigo, As you can see i did the login signup communication with socket.io,
But to follow Industry standards now i am planning to change it all with http requests in express and routes, Will you be able to do that?

**Comment by elidakirigo** [comment]
> Hey @elidakirigo, As you can see i did the login signup communication with socket.io, But to follow Industry standards now i am planning to change it all with http requests in express and routes, Will you be able to do that?

hi, @arpittyagirocks when are you doing the changes, please? i will be able to work around it, yes

**Comment by arpittyagirocks** [comment]
I want you to it, set up app.routes for sign up and login, shouldn't be hard

**Comment by elidakirigo** [comment]
> I want you to it, set up app.routes for sign up and login, shouldn't be hard

okay

**Comment by elidakirigo** [comment]
hi, @arpittyagi102 how do I work around this issue `SimpleCrypto object MUST BE initialised with a SECRET KEY.`
## screenshot

![Link-Up-error](https://github.com/arpittyagi102/LinkUp/assets/42931101/55c314f8-49fe-4c1b-beba-bcb7bc828871)

**Comment by arpittyagi102** [comment]
Either you can use a dummy value which would cause error in "Wrong Password" 
Or you may comment all the code using "bycrypt" and "cookies"
I hope it helps

**Comment by elidakirigo** [comment]
okay, thankyou, let me try

**Comment by Seckrel** [comment]
env files issue and project setup issue solved in pr #21  hope it helps

**Comment by elidakirigo** [comment]
thanks @Seckrel
