### ISSUE TITLE
Replace normal notifications with `react-hot-toast` notifications

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#43]
Hello, I want someone to use `react -hot-toast` notification in my reactjs project, it currently uses default notifications
please take reference from this [https://react-hot-toast.com/](https://react-hot-toast.com/)

**Comment by saakshiraut28** [comment]
Hey @arpittyagi102, I would like to work on this issue.

**Comment by arpittyagi102** [comment]
Hello @saakshiraut28, I have assigned you the issue. You may start working on it.

**Comment by saakshiraut28** [comment]
Hey @arpittyagi102, I'm getting the following error after setting up this project:
![image](https://github.com/arpittyagi102/LinkUp/assets/61418965/f6cb683d-1822-4643-9038-5effd4d1ad7d)

Could you please tell me how to solve it?

**Comment by arpittyagi102** [comment]
Hello @saakshiraut28, have a look at [CONRTIBUTING.md](https://github.com/arpittyagi102/LinkUp/blob/master/CONTRIBUTING.md)
Reply if that doesn't help, i will try my best to help

**Comment by saakshiraut28** [comment]
Thanks @arpittyagi102.
I just realized that I had the order mixed up—I was running the frontend server before the backend server. That could be the reason why I was getting the error.
