### ISSUE TITLE
[UI] Sign up with google cursor

### ISSUE THREAD

**Issue by Bashamega** [arpittyagi102/LinkUp#60]
Hello:)
I have noticed that when you hover over the `Signup with google` button the cursor does not change to the pointer. Which is bad user experience, and gives the user the feeling that it is disabled.

I would like to work on this issue, and I will solve it by making the cursor a pointer

**Comment by arpittyagi102** [comment]
Sure, @Bashamega I have assigned you the issue, you can start working on it, 
feel free to give any other suggestion or feedback about the project
