### ISSUE TITLE
Make Login and SignUp page responsive

### ISSUE THREAD

**Issue by arpittyagi102** [arpittyagi102/LinkUp#7]
Hello Contributors, help me make the Login and SignUp page responsive to the mobile level

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by advaithas** [comment]
Hi can I work on this

**Comment by arpittyagi102** [comment]
hello @advaithas , i am sorry, this issue has been solved, i should have closed it
i hope you find something else to contribute in this project.
